#ifndef _CG_F_H_
#define _CG_F_H_

int CG_F(cmpxGPU *b,
    cmpxGPU *vec_y,
    CULIB_HANDLES cuHandles, 
    FFT_BUFFER    fft_buffer,
    MTX_B mtx_B,
    int Nx,
    int Ny,
    int Nz,
    int Nd,
    int max_iter,
    realGPU tol,
    cmpxGPU* Pi_Qr,
    cmpxGPU* Pi_Qrs,
    cmpxGPU* Pi_Qr_110,
    cmpxGPU* Pi_Qrs_110,
    cmpxGPU* Pi_Qr_101,
    cmpxGPU* Pi_Qrs_101,
    cmpxGPU* Pi_Qr_011,
    cmpxGPU* Pi_Qrs_011,
    cmpxGPU* D_k,
    cmpxGPU* D_ks);

int CG_F(cmpxGPU *b,
    cmpxGPU *vec_y,
    CULIB_HANDLES cuHandles, 
    FFT_BUFFER    fft_buffer,
    MTX_B mtx_B,
    int Nx,
    int Ny,
    int Nz,
    int Nd,
    int max_iter,
    realGPU tol,
    cmpxGPU* Pi_Qr,
    cmpxGPU* Pi_Qrs,
    cmpxGPU* Pi_Qr_110,
    cmpxGPU* Pi_Qrs_110,
    cmpxGPU* Pi_Qr_101,
    cmpxGPU* Pi_Qrs_101,
    cmpxGPU* Pi_Qr_011,
    cmpxGPU* Pi_Qrs_011,
    cmpxGPU* D_kx,
    cmpxGPU* D_ky,
    cmpxGPU* D_kz);

#endif